name: Tox
on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - name: bandit
            python-version: 3.8
            tox-env: bandit
          - name: black
            python-version: 3.8
            tox-env: black
          - name: flake8
            python-version: 3.8
            tox-env: flake8
          - name: isort
            python-version: 3.8
            tox-env: isort
          - name: mypy
            python-version: 3.8
            tox-env: mypy
          - name: python3.5 django2
            python-version: 3.5
            tox-env: py3-django2
          - name: python3.6 django2
            python-version: 3.6
            tox-env: py3-django2
          - name: python3.6 django3
            python-version: 3.6
            tox-env: py3-django3
          - name: python3.8 django2
            python-version: 3.8
            tox-env: py3-django2
          - name: python3.8 django3
            python-version: 3.8
            tox-env: py3-django3
          - name: python3.8 django4
            python-version: 3.8
            tox-env: py3-django4
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Test with tox
        run: |
          python -m pip install --upgrade pip
          pip install tox
          tox -e ${{ matrix.tox-env }}
